Repository MeloDiary/melodiary-FE, pull requests merged in 2024-08, with the labels that each got.

#19 [Feat] 일기페이지 구현 #12
  src/App.tsx
  src/components/comment/Comment.tsx
  src/pages/Diary.tsx
Labels: Feat

#21 [Feat] 일기 작성 페이지 UI 구현 #10
  package-lock.json
  package.json
  src/App.tsx
  src/components/diary/DiaryEditor.tsx
  src/components/diary/DiaryPreview.tsx
  src/components/header/Header.tsx
  src/components/layout/Layout.tsx
  src/components/sidebar/Sidebar.tsx
  src/constants/writeDiary.ts
  src/models/diary.model.ts
  src/pages/WriteDiary.tsx
  src/styles/global.ts
  src/styles/theme.ts
Labels: Feat

#23 [Feat] 뮤직바 컴포넌트 구현 #20
  src/components/comment/Comment.tsx
  src/components/musicbar/MusicBar.tsx
  src/index.tsx
  src/pages/Diary.tsx
Labels: Feat

#26 [Feat] 마이페이지 UI 프레임만 구현 #22
  src/assets/images/mypage/mypage-bg.jpg
  src/components/mypage/AllDiaries.tsx
  src/components/mypage/MoodGraph.tsx
  src/components/mypage/Playlist.tsx
  src/components/mypage/Settings.tsx
  src/components/sidebar/Sidebar.tsx
  src/pages/MyPage.tsx
Labels: Feat

#29 [Refactor] diary컴포넌트분리 #25
  src/App.tsx
  src/components/diary/DiaryContent.tsx
  src/components/diary/DiaryFooter.tsx
  src/components/diary/DiaryHeader.tsx
  src/components/diary/DiaryItem.tsx
  src/components/layout/Layout.tsx
  src/components/sidebar/Sidebar.tsx
  src/dummyData.ts
  src/pages/Diary.tsx
Labels: Refactor

#35 [Feat] 일기 작성 페이지 추가구현
  .gitignore
  package-lock.json
  package.json
  src/api/http.ts
  src/constants/writeDiary.ts
  src/hooks/useGeoLocation.ts
  src/pages/WriteDiary.tsx
  src/styles/global.ts
Labels: Feat

#37 [Feat] explore페이지 개발 #24
  src/pages/Explore.tsx
Labels: Feat

#38 [Feat] mates페이지 #32
  src/components/sidebar/MatesSidebar.tsx
  src/pages/Mates.tsx
Labels: Feat

#39 [Feat] home diary파트 #30
  src/components/diary/DiaryItem.tsx
  src/components/musicbar/MusicBar.tsx
  src/pages/Home.tsx
  src/styles/theme.ts
Labels: Feat

#43 [Design] 폰트 및 폰트 굵기 변경 #42
  src/components/comment/Comment.tsx
  src/components/diary/Calender.tsx
  src/components/diary/PlayList.tsx
  src/components/header/BeforeLoginHeader.tsx
  src/components/header/Header.tsx
  src/components/layout/Layout.tsx
  src/components/musicbar/MusicBar.tsx
  src/config.ts
  src/context/AuthContext.tsx
  src/pages/Landing.tsx
  src/pages/MyPage.tsx
  src/styles/global.ts
Labels: Design

#48 [Fix] 뮤직바 url 이슈 해결 #20
  src/components/musicbar/MusicBar.tsx
Labels: Fix

#50 [Refactor] diary타입변경 #49
  src/components/diary/DiaryContent.tsx
  src/components/diary/DiaryFooter.tsx
  src/components/diary/DiaryHeader.tsx
  src/components/diary/DiaryItem.tsx
  src/dummyData.ts
  src/models/diary.model.ts
  src/models/notification.model.ts
  src/models/user.model.ts
Labels: Refactor

#52 [Feat] mates페이지api연결 #32
  src/api/like.api.ts
  src/api/mates.api.ts
  src/components/sidebar/MatesSidebar.tsx
  src/hooks/useLikesStatus.ts
  src/hooks/useMates.ts
  src/hooks/useMatesData.ts
  src/pages/Mates.tsx
Labels: Feat

#53 [Feat] 홈페이지 다이어리 파트 api 연결 #30
  src/api/diary.api.ts
  src/api/user.api.ts
  src/hooks/useDiary.ts
  src/hooks/useUserData.ts
  src/pages/Diary.tsx
  src/pages/Home.tsx
Labels: Feat

#54 [Feat] 헤더 API 연결 #41
  src/api/notification.api.ts
  src/api/search.api.ts
  src/components/customAlert/CustomAlert.tsx
  src/components/header/Header.tsx
  src/components/header/SearchBar.tsx
  src/components/notification/NotificationDropdown.tsx
  src/hooks/useNotification.ts
  src/hooks/useSearchResult.ts
Labels: Feat

#55 [Feat] 홈페이지 캘린더 API 연결 #45
  src/api/auth.api.ts
  src/api/home.api.ts
  src/api/http.ts
  src/api/requestMate.api.ts
  src/assets/icons/Mate.svg
  src/assets/icons/addMate.svg
  src/assets/icons/requestMate.svg
  src/components/button/AddMateButton.tsx
  src/components/diary/Calender.tsx
  src/context/AuthContext.tsx
  src/pages/Auth.tsx
  src/pages/Home.tsx
  src/pages/Join.tsx
  src/pages/Landing.tsx
  src/pages/Login.tsx
  src/pages/Nickname.tsx
Labels: Feat

#57 [Feat] 일기 작성 등록 api 연동 #27
  package-lock.json
  package.json
  public/index.html
  src/api/diary.api.ts
  src/api/http.ts
  src/api/mypage.api.ts
  src/components/diary/DiaryEditor.tsx
  src/components/diary/DiaryPreview.tsx
  src/constants/writeDiary.ts
  src/hooks/useDiary.ts
  src/hooks/useGeoLocation.ts
  src/models/diary.model.ts
  src/pages/WriteDiary.tsx
Labels: Feat

#60 [Feat] 사용자 정보 조회 및 전체 일기 조회 api 연동 #58
  src/api/mypage.api.ts
  src/components/mypage/AllDiaries.tsx
  src/components/mypage/DiaryCard.tsx
  src/hooks/useMyPage.ts
  src/models/mypage.model.ts
  src/pages/MyPage.tsx
Labels: Feat

#62 [Feat] 플레이리스트 api 연동 #59
  src/api/auth.api.ts
  src/api/home.api.ts
  src/api/http.ts
  src/api/logoutUtility.ts
  src/api/requestMate.api.ts
  src/components/button/AddMateButton.tsx
  src/components/diary/PlayList.tsx
  src/config.ts
  src/pages/Auth.tsx
Labels: Feat

#63 [Feat] home 다이어리 api 연결 #30
  src/api/comment.api.ts
  src/components/comment/Comment.tsx
  src/components/diary/DiaryContent.tsx
  src/components/diary/DiaryFooter.tsx
  src/components/diary/DiaryItem.tsx
  src/components/musicbar/MusicBar.tsx
  src/hooks/useComment.ts
  src/hooks/useLikeStatus.ts
  src/models/comment.model.ts
  src/pages/Diary.tsx
  src/pages/Home.tsx
Labels: Feat

#64 [Feat] 마이페이지 환경설정 api 연동 #61
  src/api/mypage.api.ts
  src/components/mypage/DiaryCard.tsx
  src/components/mypage/Settings.tsx
  src/hooks/useMyPage.ts
  src/styles/theme.ts
Labels: Feat

#68 [Feat] diary update,delete api 연결 #67
  src/api/diary.api.ts
  src/components/customAlert/CustomAlert.tsx
  src/components/diary/DiaryHeader.tsx
  src/components/header/SearchBar.tsx
  src/hooks/useDiary.ts
  src/pages/WriteDiary.tsx
Labels: Feat

#69 [Refactor] 작성된 일기 미리보기 리팩토링 #66
  src/api/diary.api.ts
  src/components/customAlert/CustomAlert.tsx
  src/components/diary/DiaryHeader.tsx
  src/components/diary/DiaryPreview.tsx
  src/components/header/SearchBar.tsx
  src/hooks/useDiary.ts
  src/pages/WriteDiary.tsx
Labels: Refactor

#70 [Feat] 마이페이지 플레이리스트 구현 #65
  src/api/http.ts
  src/components/diary/Calender.tsx
  src/components/diary/PlayList.tsx
  src/components/mypage/Playlist.tsx
  src/context/AuthContext.tsx
  src/pages/Auth.tsx
  src/pages/MyPage.tsx
  src/pages/Nickname.tsx
  src/pages/WriteDiary.tsx
  src/util/logoutUtility.ts
Labels: Feat

#79 [Feat] comment API 연결 #73
  src/api/comment.api.ts
  src/components/comment/Comment.tsx
  src/hooks/useComment.ts
  src/models/comment.model.ts
  src/pages/Home.tsx
Labels: Feat

#80 [Feat] 친구삭제 API 연결 #32
  src/api/mates.api.ts
  src/components/button/AddMateButton.tsx
  src/components/diary/DiaryContent.tsx
  src/components/notification/NotificationDropdown.tsx
  src/components/sidebar/MatesSidebar.tsx
  src/hooks/useMates.ts
  src/hooks/useMatesData.ts
  src/models/user.model.ts
  src/pages/Explore.tsx
  src/pages/Mates.tsx
Labels: Feat

#77 [Feat] 마이페이지 기분그래프 구현 #74
  package-lock.json
  package.json
  src/api/mypage.api.ts
  src/components/diary/DiaryPreview.tsx
  src/components/mypage/MoodGraph.tsx
  src/hooks/useMyPage.ts
  src/models/mypage.model.ts
  src/pages/WriteDiary.tsx
Labels: Feat

#83 [Feat] 마이페이지 프로필,배경 변경 #72
  src/api/uploadProfileImage.ts
  src/config.ts
  src/pages/Join.tsx
  src/pages/Login.tsx
  src/pages/MyPage.tsx
Labels: Feat

#82 [Feat] 에러바운더리 #81
  src/App.tsx
  src/components/error/ErrorBoundary.tsx
  src/hooks/useDiary.ts
  src/hooks/useMates.ts
  src/hooks/useMyPage.ts
  src/index.tsx
  src/pages/Diary.tsx
  src/pages/Explore.tsx
  src/pages/Home.tsx
  src/pages/Mates.tsx
  src/pages/MyPage.tsx
Labels: Feat

#85 [Feat] 도움말 기능 구현 #84
  src/assets/images/help/001.png
  src/assets/images/help/002.png
  src/assets/images/help/003.png
  src/assets/images/help/004.png
  src/assets/images/help/005.png
  src/assets/images/help/006.png
  src/assets/images/help/007.png
  src/assets/images/help/008.png
  src/assets/images/help/009.png
  src/assets/images/help/010.png
  src/assets/images/help/011.png
  src/components/header/Header.tsx
  src/components/help/HelpOverlay.tsx
  src/pages/Nickname.tsx
Labels: Feat

#90 [Feat] 일기작성페이지 s3 이미지 api 연동 및 수정 #78
  package-lock.json
  package.json
  src/api/diary.api.ts
  src/components/diary/DiaryEditor.tsx
  src/components/diary/DiaryPreview.tsx
  src/components/mypage/AllDiaries.tsx
  src/constants/writeDiary.ts
  src/pages/WriteDiary.tsx
Labels: Feat, Style

#87 [Refactor] Diary 이미지 슬라이드 적용 #86
  package-lock.json
  package.json
  src/components/diary/DiaryContent.tsx
  src/components/diary/DiaryItem.tsx
Labels: Refactor

#89 [Refactor]Explore 및 Mates 페이지에 무한 스크롤 기능 추가, UI 개선 #88
  src/api/explore.api.ts
  src/api/http.ts
  src/api/mates.api.ts
  src/components/layout/Layout.tsx
  src/components/sidebar/MatesSidebar.tsx
  src/hooks/useExplore.ts
  src/hooks/useMatesData.ts
  src/pages/Explore.tsx
  src/pages/Home.tsx
  src/pages/Mates.tsx
Labels: Refactor

#92 [Feat] 마이페이지 전체일기조회 무한스크롤 #91
  package-lock.json
  src/api/mypage.api.ts
  src/components/diary/DiaryEditor.tsx
  src/components/mypage/AllDiaries.tsx
  src/components/mypage/DiaryCard.tsx
  src/components/mypage/MoodGraph.tsx
  src/components/mypage/Settings.tsx
  src/components/sidebar/Sidebar.tsx
  src/hooks/useDiary.ts
  src/hooks/useMyPage.ts
  src/pages/WriteDiary.tsx
Labels: Feat
